# Generated by Django 3.2.14 on 2022-11-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AddField(
            model_name='ciudad',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='puntuacion',
            field=models.FloatField(default=0, null=True, verbose_name='Puntuación'),
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('url', models.URLField(max_length=255, null=True)),
                ('puntuacion', models.FloatField(default=0, null=True, verbose_name='Puntuación')),
                ('vistas', models.IntegerField(default=0, verbose_name='Vistas')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciudad')),
            ],
        ),
        migrations.RenameModel(
            old_name='Destino',
            new_name='Atraccion',
        ),
        migrations.AlterModelOptions(
            name='atraccion',
            options={'verbose_name_plural': 'Atracciones'},
        ),
    ]
