# Generated by Django 3.2.14 on 2022-11-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221114_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destino',
            new_name='Atraccion',
        ),
        migrations.AlterModelOptions(
            name='atraccion',
            options={'verbose_name_plural': 'Atracciones'},
        ),
    ]
