# Generated by Django 3.2.14 on 2022-12-13 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_comentariogustado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAtraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(null=True, verbose_name='mensaje')),
                ('likes', models.IntegerField(default=0, verbose_name='Comentario Likes')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('atraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atraccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioGustadoAtraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comentarioatraccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
